export const INIT_TRAINING = 'INIT_TRAINING';
export const START_TRAINING = 'START_TRAINING';
export const PAUSE_TRAINING = 'PAUSE_TRAINING';
export const GO_TO_SET = 'GO_TO_SET';
export const NEXT_REPETITION = 'NEXT_REPETITION';
export const QUIT_TRAINING = 'QUIT_TRAINING';