export const INIT_TRAINING = 'INIT_TRAINING';
export const START_TRAINING = 'START_TRAINING';
export const GO_TO_PIPE_INDEX = 'GO_TO_PIPE_INDEX';

export const PAUSE_TRAINING = 'PAUSE_TRAINING';
export const QUIT_TRAINING = 'QUIT_TRAINING';
